# Generated by Django 5.1.6 on 2025-02-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happsay_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={"managed": True},
        ),
    ]
