# Generated by Django 5.1.6 on 2025-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happsay_app", "0004_rename_user_id_fk_todolist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="deadline",
            field=models.DateField(),
        ),
    ]
